---
apiVersion: v1
kind: Service
metadata:
  name: email-service
  labels:
    app: email-service
spec:
  ports:
  - port: 3025
    name: smtp
  - port: 3143
    name: imap
  clusterIP: None
  selector:
    app: email-service
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: email-service
spec:
  selector:
    matchLabels:
      app: email-service
  serviceName: "email-service"
  replicas: 3
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: email-service
    spec:
      containers:
      - name: email-service
        image: greenmail/standalone:1.6.7
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3025
          name: smtp
        - containerPort: 3143
          name: imap
        env:
          - name: GREENMAIL_OPTS
            value: "-Dgreenmail.verbose -Dgreenmail.hostname=0.0.0.0 -Dgreenmail.setup.test.smtp -Dgreenmail.setup.test.imap -Dgreenmail.users=user1:password1,user2:password2"
